### ISSUE TITLE
Impersonate error on hot code reload

### ISSUE THREAD

**Issue by joerodrig** [MeteorToys/allthings#15] opened 2015-06-25 06:31 UTC
After updating to the latest version, I seem to be getting a server ever whenever I update my code from impersonate:

```
Exception while invoking method 'MeteorToys_impersonate' TypeError: undefined is not a function
at [object Object].Meteor.(anonymous function).MeteorToys_impersonate
at maybeAuditArgumentChecks (app/.meteor/local/build/programs/server/packages/ddp.js:2445:12)
at app/.meteor/local/build/programs/server/packages/ddp.js:1476:20
at [object Object]._.extend.withValue (app/.meteor/local/build/programs/server/packages/meteor.js:989:17)
app/.meteor/local/build/programs/server/packages/ddp.js:1475:41

at [object Object]._.extend.withValue app/.meteor/local/build/programs/server/packages/meteor.js:989:17)

at [object Object]._.extend.protocol_handlers.method (app/.meteor/local/build/programs/server/packages/ddp.js:1474:51)

at app/.meteor/local/build/programs/server/packages/ddp.js:1374:43
```

I've reset my impersonate collection a few times . I'll also try re-adding the whole package later.

**Comment by msavin** [comment] 2015-06-25 17:05
Nice, looks like a fun afternoon ahead :) 

Can you please send a list of your packages?

**Comment by joerodrig** [comment] 2015-06-25 17:30
Here are my packages:

```
meteor-platform
mizzao:bootstrap-3
meteortoys:allthings
iron:router
accounts-google
service-configuration
http
random
simple:reactive-method
reactive-var
kevohagan:sweetalert

# -- Schema & Form Packages --
aldeed:collection2
aldeed:autoform
rajit:bootstrap3-datepicker
aldeed:autoform-bs-datepicker

# -- Collection Security Package --
ongoworks:security

#  -- Testing Packages --
sanjo:jasmine
velocity:html-reporter

# -- LINK Packages --
joerodrig3:link-base
joerodrig3:link-account
joerodrig3:link-account-api
joerodrig3:link-collections
joerodrig3:link-course
joerodrig3:link-course-api
joerodrig3:link-router
joerodrig3:link-course-visualization
```

Let me know if you need anything else and goodluck!

**Comment by msavin** [comment] 2015-07-02 03:30
Thanks for the heads up - hoping to have a fix tomororw

**Comment by mordrax** [comment] 2015-07-30 03:35
I had to revert to 1.0 from 1.1.4 for impersonation, but 1.2 seems to work. Can you confirm this @joerodrig3?

**Comment by msavin** [comment] 2015-08-08 13:56
I've tested it in 1.2.3 and it works fine. Can you please confirm if this is still an issue?

**Comment by msavin** [comment] 2015-08-11 13:37
Closing on the assumption that the problem is resolved. If not, please lmk

**Closed as completed** 2015-08-11 13:37 UTC
